from datetime import datetime
from agents.report_agent.state import ReportAgentState


def format_node(state: ReportAgentState) -> dict:
    symbol = state["symbol"]
    errors = state.get("errors", [])
    report_id = f"RPT-{symbol}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    generated_at = datetime.now().isoformat()

    print(f"📋 Formatting full report for {symbol}...")

    full_report = f"""
╔══════════════════════════════════════════════════════════════╗
║           FINSIGHT INVESTMENT RESEARCH REPORT               ║
╠══════════════════════════════════════════════════════════════╣
║  Symbol:    {symbol:<10}  Report ID: {report_id:<25} ║
║  Price:     ${state.get("current_price", "N/A"):<10}  Generated:  {generated_at[:10]:<25} ║
║  Sector:    {str(state.get("sector", "N/A")):<48} ║
╚══════════════════════════════════════════════════════════════╝

━━━ EXECUTIVE SUMMARY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{state.get("executive_summary", "N/A")}

━━━ FINANCIAL ANALYSIS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{state.get("financial_analysis", "N/A")}

KEY METRICS:
    Revenue (TTM):   ${state.get("revenue", 0):>20,.0f}
    EPS:             {str(state.get("eps", "N/A")):>20}
    P/E Ratio:       {str(state.get("pe_ratio", "N/A")):>20}
    Profit Margin:   {str(state.get("profit_margin", "N/A")):>20}
    Market Cap:      ${state.get("market_cap", 0):>20,.0f}

━━━ TECHNICAL ANALYSIS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{state.get("technical_analysis", "N/A")}

INDICATORS:
    SMA 20:          {str(state.get("sma_20", "N/A")):>20}
    SMA 50:          {str(state.get("sma_50", "N/A")):>20}
    RSI:             {str(state.get("rsi", "N/A")):>20}
    Volatility:      {str(state.get("volatility", "N/A")):>19}%
    Golden Cross:    {str(state.get("golden_cross", "N/A")):>20}
    Momentum:        {str(state.get("momentum_signal", "N/A")):>20}

━━━ RISK ASSESSMENT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{state.get("risk_assessment", "N/A")}

    Risk Score:      {str(state.get("risk_score", "N/A")):>19}/10
    Risk Label:      {str(state.get("risk_label", "N/A")):>20}
    Beta:            {str(state.get("beta", "N/A")):>20}

━━━ RECOMMENDATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    ⭐ {state.get("recommendation", "HOLD").upper()}

{state.get("recommendation_section", "N/A")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER: This report is generated by AI for informational
purposes only. Not financial advice. Do your own research.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    print(f"✅ format_node → Report formatted | ID: {report_id}")
    return {
        "full_report": full_report,
        "report_id": report_id,
        "generated_at": generated_at,
        "errors": errors,
    }
